workers = 2

[directories]
# Relative paths will be resolved based on project directory
  # if no 'root' is defined 
# in_dir: directory for data files (i.e. short reads)
# out_dir: directory for file processing outputs
# ref_dir: directory for reference genome assemblies
# tmp_dir: directory for temporary files
# rep_dir: directory for supplementary stats & reports

in_dir = './reads'
out_dir = './output'
ref_dir = './refs'
tmp_dir = './tmp'
rep_dir = './output/reports'

[flags]
pair = ['_1', '_2']
fastp = 'clean'
dedup = 'dedup'

[input]
main_ref = 'ref_genome.norm.fa'

# options.<tool> - follows syntax of options specified by
  # the tool; set flags to true
[options.fastp]
thread = 8
trim_poly_g = true
detect_adapter_for_pe = true
dont_eval_duplication = true
length_required = 80
length_limit = 160
qualified_quality_phred = 20

[options.bwamem2_mem]
t = 11

[options.minibwa_map]
t = 11

[options.sam_collate]
threads = 8
output-fmt = 'SAM'
u = true

[options.sam_fixmate]
threads = 5
output-fmt = 'SAM'
m = true

[options.sam_sort]
threads = 5
m = '29491M'
output-fmt = 'SAM'
u = true

[options.sam_markdup]
threads = 5
output-fmt = 'BAM'
r = true
s = true

[options.sam_faidx]
threads = 2

[options.bcftools_mpileup]
threads = 11
d = 8000
ambig-reads = 'drop'
annotate = 'AD,DP,SP,SCR'
output-type = 'b7'