workers = 4

[directories]
# Relative paths will be resolved based on project directory
  # if no 'root' is defined 

# root: root directory for resolving other project directories
# in_dir: directory for data files (i.e. short reads)
# out_dir: directory for file processing outputs
# ref_dir: directory for reference genome assemblies
# tmp_dir: directory for temporary files
# rep_dir: directory for supplementary stats & reports

#root = '.'
in_dir = './reads'
out_dir = './output'
ref_dir = './refs'
tmp_dir = './tmp'
rep_dir = './output/reports'

[slurm]
email = 'test.id@gmail.com'
username = 'test.id'
partition = ['batch','debug']

# input.<tool> - additional info related to input files
# options.<tool> - follows syntax of options specified by
  # the tool; set flags to true

# flag_type: position of read identifier in filename
# read1_flag: identifier for 1st read in paired-end data
# read2_flag: identifier for 2nd read in paired-end data
# ref_file: primary reference genome file to use
[input.fastp]
flag_type = 'suffix'
read1_flag = '_1'
read2_flag = '_2'
read_flags = ['_1', '_2']

[options.fastp]
thread = 4
trim_poly_g = true
detect_adapter_for_pe = true
dont_eval_duplication = true
length_required = 80
qualified_quality_phred = 20

[input.bwa_mem]
ref_file = 'Mtex-Abuab_RBK.fa'
prep_ext = '.clean.fastq.gz'

[options.bwa_index]
t = 8

[options.bwa_mem]
t = 8

[options.bcftools_mpileup]
threads = 8
ambig-reads = 'drop'
annotate = 'AD,SD,SP'
output-type = 'v'